---
- hosts: dev
  become: true
  tasks:
    - name: update yum packages
      yum:
        name: "*"
        state: latest
    - name: install docker
      yum:
        name: docker
        state: present
    - name: start the docker service
      service:
        name: docker
        state: started
        enabled: true
