---
- hosts: dev
  become: True
  tasks:
     - name: install an apple
        command: "{{item}}"
          with_items:
             - sudo dnf config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo
             - sudo dnf install docker-ce --nobest -y
             - sudo systemctl enable docker
             - sudo systemctl start docker
      
     - name: Start the container
       docker_container:
         name: sampleapp
         image: "sahilthakre123/sampleapp:{{DOCKER_TAG}}"
         state: started
         published_ports:
           - 0.0.0.0:8553:8080
