---
- name: Install Docker and Python
  hosts: dev
  become: true
  tasks:
    - name: Install Docker
      yum:
        name: docker
        state: present
    - name: Start Docker Service
      service:
        name: docker
        state: started
    - name: Install python
      yum:
        name: python
        state: present
