---
- name: Install Docker and Python
  hosts: dev
  become: true
  tasks:
    - name: Install Docker
      yum:
        name: docker
        state: present
    - name: Start Docker Service
      service:
        name: docker
        state: started
    - name: Install python
      yum:
        name: python
        state: present
    - name: Pull the samba1295/sampleapp:{{DOCKER_TAG}}
      docker_image:
        name: samba1295/sampleapp:{{DOCKER_TAG}}
        tags: latest
    - name: Run the container
      docker_container:
        name: sampleapp
        image: samba1295/sampleapp:{{DOCKER_TAG}}
        state: started
        ports:
          - 8553:8080
