---
- hosts: dev
  become: true
  tasks:
    - name: update yum packages
      yum:
        name: "*"
        state: latest
    - name: install docker
      yum:
        name: docker
        state: present
    - name: start the docker service
      service:
        name: docker
        state: started
        enabled: true
    - docker_container:
        image: samba1295/sampleapp:{{DOCKER_TAG}}
        name: sampleapp
        published_ports:
          - 0.0.0.0:8553:8080
        state: started
